dist: xenial
language: python
python: 3.7
env:
  global:
  - VERSION=$TRAVIS_TAG

install:
- pip install -r requirements.txt
- pip install -e .

script:
- pytest
- python setup.py sdist bdist_wheel

deploy:
  - provider: releases
    api_key:
      secure: EiD3S2CdpRZOoVvr/Rl7wyxoiX/zbtbkRu1YI1MxHU39fK4lcN/ikeumbfgrkr6IaqWS2VhivT29rJUKh71eYi9SWumDkGVoZim3ikRyBkd1lVMEtF8Jfjfg3sntUaU7afrrGbvcArpgzY1FD9oLiOmOO+V59MkvuUmlAvNbmkjKtwIkE4pOYTasxfGZDo48mLPs4V9we4LuVL8WIkeJJ3vxBoub7Z8mf3hsNnel8dgcAgrElPpsMX0dIUF/CqswErVLk3N+BUmRwRPRQEoyQ3mypUR/EkBKjYo2/a6cWQX6KHLlEF+4bRp+YeMebq3I5XeYeGg0MPtZ4/XrSd4ukTqtn/jkb2oOUlpyzSioWKX3DLU8AQy2U7KK5LPVJT96+4v1q5G6ouQ23aMHW4DziRFl4/ZVNmcLHtaXrao+df2grzQ+nalEm2ph9vJwn2Z/fgUBzESoLtF2WM7Ax5XFf1JOoCVId71tMmws8VafrPT4DwbrMTq9VoDS6QfdPOMyorwnP/3qA0/bZhDNOXFGlEkHqi765R/jdBczdQyubVgYr8kLAw4jB1FE328NPzjr4EID+NX21uM4hSsFIQA+Ds21r00DVozvwYJesq8Jzd0D0MWghbZvdp4s0tvaXjBhuA49ekd7SBavA1QDzCN+DmpnHseamc6ueMDt4afCmH8=
    file:
    - dist/thumbtack_client-$VERSION.tar.gz
    - dist/thumbtack_client-$VERSION-py2.py3-none-any.whl
    skip_cleanup: true
    on:
      tags: true
  - provider: pypi
    user: __token__
    password:
      secure: "TAoqCYVptJwtiBibrFVKLTUBo8pnOl6jxNK1xSUSqmDw6UKuNzZcbFoNKWH7OMs72ekGKay0SJpHd8hSHEF85t7ogtlrHw9CtbyIOJBZPsIjp+hZmms8EeFw82z7P6DvrUrbdrrVurFea7nga5CxjllodbF4uhEx1OxWyIiYh+LJfhfeQOVOYyN6sShra6eOoZtmyQjfpisv2tMnTbNrItwi8uB8GPfsxY2sTesrjHb2gHLqgdTFTn0GE+nF+qb6TqmhZIoVGJjldotzLDeBpPtMe5a+B5WTibIr36MSAJGuu3uZj+YAwgQrKM0ux015AGRo3wRaOuZwLby71DWYTLwcb9EL1gXxflmAiSf9Znd2E+E/ssK9TVSQvLdkc59ZheBy9QbhNISKM9kOs3qScyORJsaPgflhWZnaV2SXybu0DdoWUKGJGGTHb2HwnGSqT4mUngir/DEtuZXaDxQI8ijAZbMRr7Tm+gEAFiM/KDCheMjnC+DQUcafnZjJJtY7bIMZ9DhHEjnGNSsJJYeGA+zLfiJOXjDFAvcOnGdfTaAjHxxoO+AvTF8Xkf5CGYfcgKxeIbkso8mr6QqWy7JjGCsXDa+Q/4er1zFg/IIgnbjhwcr6Q//cVOaGcbC2DgdCFiD06wG/vnU6czyS8T/waNe/ivHhEwmPbZZK/kZ5urg="
    skip_cleanup: true
    on:
      tags: true

