dist: xenial
language: python
python: 3.7
env:
  global:
    - VERSION=$TRAVIS_TAG

install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  - pytest

deploy:
  provider: releases
  api_key:
    secure: "EiD3S2CdpRZOoVvr/Rl7wyxoiX/zbtbkRu1YI1MxHU39fK4lcN/ikeumbfgrkr6IaqWS2VhivT29rJUKh71eYi9SWumDkGVoZim3ikRyBkd1lVMEtF8Jfjfg3sntUaU7afrrGbvcArpgzY1FD9oLiOmOO+V59MkvuUmlAvNbmkjKtwIkE4pOYTasxfGZDo48mLPs4V9we4LuVL8WIkeJJ3vxBoub7Z8mf3hsNnel8dgcAgrElPpsMX0dIUF/CqswErVLk3N+BUmRwRPRQEoyQ3mypUR/EkBKjYo2/a6cWQX6KHLlEF+4bRp+YeMebq3I5XeYeGg0MPtZ4/XrSd4ukTqtn/jkb2oOUlpyzSioWKX3DLU8AQy2U7KK5LPVJT96+4v1q5G6ouQ23aMHW4DziRFl4/ZVNmcLHtaXrao+df2grzQ+nalEm2ph9vJwn2Z/fgUBzESoLtF2WM7Ax5XFf1JOoCVId71tMmws8VafrPT4DwbrMTq9VoDS6QfdPOMyorwnP/3qA0/bZhDNOXFGlEkHqi765R/jdBczdQyubVgYr8kLAw4jB1FE328NPzjr4EID+NX21uM4hSsFIQA+Ds21r00DVozvwYJesq8Jzd0D0MWghbZvdp4s0tvaXjBhuA49ekd7SBavA1QDzCN+DmpnHseamc6ueMDt4afCmH8="
  file:
    - dist/thumbtack_client-$VERSION.tar.gz
    - dist/thumbtack_client-$VERSION-py2.py3-none-any.whl
  skip_cleanup: true
  on:
    tags: true
