dist: xenial
language: python
python: 3.7
env:
  global:
  - VERSION=$TRAVIS_TAG

install:
- pip install -r requirements.txt
- pip install -e .

script:
- pytest
- python setup.py sdist bdist_wheel

deploy:
  - provider: releases
    api_key:
      secure: "psW6in+WWiDkdGZTrX/kAAeIh5QnZtgdk8hV0O6NbBDkCkZoV6vx22oHxjc4ty/VEQ1XlA566cbdwjevy8xkgaeuzSSaX1uyEcVMpmUOQlYSUXHfCg89ea9RGjzJtKo5jHKH9Q9ylPzDHH5rZRpVYhUPMvglUhmyEZEOmJm5l9gQ1cgaBR1zgLBkUSfmceLz5ha5pwb6hjGzS20pPKQA3qC8uwq7bg38vXtjJFIGd/WNakDIB0uHDjZn9cKYf9HV1CcmLmmxrGXgVk8ke3JmMR3SOuzuOwpqjFPagYzjVdQtEfBrCkpYc/IEUmHbZHDUbgXj96SYNHENFVrrMY2NSjsG0FGsBGvzaGxUZb7miJG1vFc1Cs0VUrkGAqh/kY2FoBDj62GlEgcZuBsaVVCtGBwfnsUm6L2tqD2HP/TD775Qhz7OUl/9956Cqnyn1BE6Wj2qyvBb8hbZSzAurGUHX/re0yQyx6mMHvT7b1S9EdEBl2/13di0lzd6qKYkDFRNPxOHBuURW9aSQjnypOezdx53NStYdBnpbbEOlgwvSpxBE3jid95AoQqJz8rftsiiB0Jhjabnsj2q7GtuRyLvwyDeygETnNAABemB9UZ4PPq140zS1BzLLKCUhxhsI2AXwiJm0UmY1t6bRMRsXvv5IDS54eS0x78DNPHZz4hyXxY="
    file:
    - dist/thumbtack_client-$VERSION.tar.gz
    - dist/thumbtack_client-$VERSION-py2.py3-none-any.whl
    skip_cleanup: true
    on:
      tags: true
  - provider: pypi
    user: __token__
    password:
      secure: "TAoqCYVptJwtiBibrFVKLTUBo8pnOl6jxNK1xSUSqmDw6UKuNzZcbFoNKWH7OMs72ekGKay0SJpHd8hSHEF85t7ogtlrHw9CtbyIOJBZPsIjp+hZmms8EeFw82z7P6DvrUrbdrrVurFea7nga5CxjllodbF4uhEx1OxWyIiYh+LJfhfeQOVOYyN6sShra6eOoZtmyQjfpisv2tMnTbNrItwi8uB8GPfsxY2sTesrjHb2gHLqgdTFTn0GE+nF+qb6TqmhZIoVGJjldotzLDeBpPtMe5a+B5WTibIr36MSAJGuu3uZj+YAwgQrKM0ux015AGRo3wRaOuZwLby71DWYTLwcb9EL1gXxflmAiSf9Znd2E+E/ssK9TVSQvLdkc59ZheBy9QbhNISKM9kOs3qScyORJsaPgflhWZnaV2SXybu0DdoWUKGJGGTHb2HwnGSqT4mUngir/DEtuZXaDxQI8ijAZbMRr7Tm+gEAFiM/KDCheMjnC+DQUcafnZjJJtY7bIMZ9DhHEjnGNSsJJYeGA+zLfiJOXjDFAvcOnGdfTaAjHxxoO+AvTF8Xkf5CGYfcgKxeIbkso8mr6QqWy7JjGCsXDa+Q/4er1zFg/IIgnbjhwcr6Q//cVOaGcbC2DgdCFiD06wG/vnU6czyS8T/waNe/ivHhEwmPbZZK/kZ5urg="
    skip_cleanup: true
    on:
      tags: true

