dist: xenial
language: python
python: 3.7
env:
  global:
  - VERSION=$TRAVIS_TAG

install:
- pip install -r requirements.txt
- pip install -e .

script:
- pytest
- python setup.py sdist bdist_wheel

deploy:
  - provider: releases
    api_key:
      secure: EiD3S2CdpRZOoVvr/Rl7wyxoiX/zbtbkRu1YI1MxHU39fK4lcN/ikeumbfgrkr6IaqWS2VhivT29rJUKh71eYi9SWumDkGVoZim3ikRyBkd1lVMEtF8Jfjfg3sntUaU7afrrGbvcArpgzY1FD9oLiOmOO+V59MkvuUmlAvNbmkjKtwIkE4pOYTasxfGZDo48mLPs4V9we4LuVL8WIkeJJ3vxBoub7Z8mf3hsNnel8dgcAgrElPpsMX0dIUF/CqswErVLk3N+BUmRwRPRQEoyQ3mypUR/EkBKjYo2/a6cWQX6KHLlEF+4bRp+YeMebq3I5XeYeGg0MPtZ4/XrSd4ukTqtn/jkb2oOUlpyzSioWKX3DLU8AQy2U7KK5LPVJT96+4v1q5G6ouQ23aMHW4DziRFl4/ZVNmcLHtaXrao+df2grzQ+nalEm2ph9vJwn2Z/fgUBzESoLtF2WM7Ax5XFf1JOoCVId71tMmws8VafrPT4DwbrMTq9VoDS6QfdPOMyorwnP/3qA0/bZhDNOXFGlEkHqi765R/jdBczdQyubVgYr8kLAw4jB1FE328NPzjr4EID+NX21uM4hSsFIQA+Ds21r00DVozvwYJesq8Jzd0D0MWghbZvdp4s0tvaXjBhuA49ekd7SBavA1QDzCN+DmpnHseamc6ueMDt4afCmH8=
    file:
    - dist/thumbtack_client-$VERSION.tar.gz
    - dist/thumbtack_client-$VERSION-py2.py3-none-any.whl
    skip_cleanup: true
    on:
      tags: true
  - provider: pypi
    user: jondricek
    password:
      secure: lFYvZzL14k6p0Gy8FNGfWlyoJObtRBSfL+2svJ+TuECP9pPujCYY/+F/kljZtIqDSW9BAUeZDuMoh4MKl+AumnKV1dU9urZw4/8oVRYIruONJfM20NmU/IVA9jn7ShKJQvJjTLtZDA4FCpXtCefT8ADwq1Qnb7X4qNOmWJ573Sr1M5hMelAJFSydZOTku4Pt/Je6KVfVxX3rEeq84A4CUYELg4tT/WkfSTuE+kuZQfPg9qov5or9zmQZKFSbXUewoC0OAvipRfdurR6gbJKI740HG1yqyBjTjqhBuQRtQ7HTGbCzX+VTae0fUbSE48DwWoJUJASdie+9FFrJIm5E/useWhWtFbFXgfK2zWvl3IKZbau0C/pszH+VYsnVI5ZH4/S2BuPlaUINWQKJi9GUCyrDRTq8AdjmMAzWflcsXQFZ8cMxWlU26KxV+GWlkqOGDvWfI7gTVrUuHDPfq4rGWAS8AH5OGAHdxMU7tKHpc33GPie+4PCkAD8BRuq0sqzI5CFeVpZzHg3S4btCVDhEPfHyWBa890eXhIngk+B7cfP+8Iyz+ehZ6SntOsVecYpwI1Zh8/1bqE35tZ0i6rAAgXHc7oXnpv/gFZQrGBQiynuXP6kAmpLhxI8hQijB3V5Dyz1k6vrigAGmye0YHkAUN94UHX7//6UoSdqYNP253jQ=
    skip_cleanup: true
    on:
      tags: true

